/**
 * Static seed fixtures.
 *
 * Kept separate from `seed.ts` so the data can be inspected, diffed and unit
 * tested without pulling in a database connection.
 *
 * Coordinates are real Tehran locations so the PostGIS radius/bbox queries
 * return sensible results when you pan the map around the city.
 */

export interface SeedCategory {
  slug: string;
  name: string;
  nameFa: string;
  icon: string;
  color: string;
  position: number;
}

export const CATEGORIES: SeedCategory[] = [
  { slug: 'languages', name: 'Languages', nameFa: 'زبان', icon: 'translate', color: '#2563eb', position: 0 },
  { slug: 'programming', name: 'Programming', nameFa: 'برنامه‌نویسی', icon: 'code', color: '#7c3aed', position: 1 },
  { slug: 'music', name: 'Music', nameFa: 'موسیقی', icon: 'music-note', color: '#db2777', position: 2 },
  { slug: 'arts', name: 'Arts', nameFa: 'هنر', icon: 'palette', color: '#ea580c', position: 3 },
  { slug: 'academic-tutoring', name: 'Academic Tutoring', nameFa: 'تدریس خصوصی', icon: 'menu-book', color: '#0891b2', position: 4 },
  { slug: 'test-prep', name: 'Test Preparation', nameFa: 'آمادگی آزمون', icon: 'fact-check', color: '#16a34a', position: 5 },
  { slug: 'business', name: 'Business', nameFa: 'کسب و کار', icon: 'business-center', color: '#4f46e5', position: 6 },
  { slug: 'sports', name: 'Sports', nameFa: 'ورزش', icon: 'sports-soccer', color: '#dc2626', position: 7 },
];

export interface SeedInstitute {
  slug: string;
  name: string;
  shortDescription: string;
  description: string;
  address: string;
  city: string;
  province: string;
  lat: number;
  lng: number;
  phone: string;
  categorySlugs: string[];
  skills: string[];
  amenities: string[];
  verification: 'UNVERIFIED' | 'PENDING' | 'VERIFIED' | 'REJECTED';
  published: boolean;
  freePreRegistration: boolean;
  commissionPercent: number;
  /** Average rating the generated reviews should approximate. */
  targetRating: number;
  reviewCount: number;
}

/**
 * Twelve institutes spread across Tehran. The mix is deliberate so every
 * discovery filter has both matching and non-matching rows:
 *   - 7 verified, 2 pending, 2 unverified, 1 rejected
 *   - ratings from 3.4 to 4.9 (so `minRating=4.5` is a real filter)
 *   - one unpublished, to prove it never appears in public search
 */
export const INSTITUTES: SeedInstitute[] = [
  {
    slug: 'pardis-language-academy',
    name: 'Pardis Language Academy',
    shortDescription: 'IELTS and Business English since 2004',
    description:
      'Pardis Language Academy has trained over 20,000 students in general and exam-focused English. '
      + 'Small classes, Cambridge-certified instructors and a free placement test for every applicant.',
    address: 'No. 120, Valiasr St, above Vanak Sq, Tehran',
    city: 'Tehran',
    province: 'Tehran',
    lat: 35.7575,
    lng: 51.4100,
    phone: '09188776655',
    categorySlugs: ['languages', 'test-prep'],
    skills: ['ielts', 'toefl', 'business-english', 'conversation'],
    amenities: ['parking', 'wifi', 'library', 'cafeteria'],
    verification: 'VERIFIED',
    published: true,
    freePreRegistration: true,
    commissionPercent: 10,
    targetRating: 4.7,
    reviewCount: 9,
  },
  {
    slug: 'tehran-code-school',
    name: 'Tehran Code School',
    shortDescription: 'Full-stack bootcamps with job placement',
    description:
      'Project-based bootcamps in web and mobile development. Every cohort ends with a portfolio '
      + 'review and introductions to our hiring partners.',
    address: 'No. 8, Beheshti Ave, Tehran',
    city: 'Tehran',
    province: 'Tehran',
    lat: 35.7290,
    lng: 51.4180,
    phone: '09177889900',
    categorySlugs: ['programming', 'business'],
    skills: ['javascript', 'python', 'react', 'nodejs', 'flutter'],
    amenities: ['wifi', 'parking', 'lab', 'lounge'],
    verification: 'VERIFIED',
    published: true,
    freePreRegistration: true,
    commissionPercent: 12,
    targetRating: 4.9,
    reviewCount: 14,
  },
  {
    slug: 'nava-music-institute',
    name: 'Nava Music Institute',
    shortDescription: 'Persian and classical instruments',
    description:
      'Traditional Persian instruments alongside piano and violin, taught one-to-one or in small '
      + 'ensembles. Annual student recital at Vahdat Hall.',
    address: 'No. 45, Enghelab St, Tehran',
    city: 'Tehran',
    province: 'Tehran',
    lat: 35.7010,
    lng: 51.3940,
    phone: '09166554433',
    categorySlugs: ['music', 'arts'],
    skills: ['piano', 'setar', 'tar', 'violin', 'vocals'],
    amenities: ['soundproof-rooms', 'instrument-rental', 'wifi'],
    verification: 'VERIFIED',
    published: true,
    freePreRegistration: true,
    commissionPercent: 8,
    targetRating: 4.6,
    reviewCount: 7,
  },
  {
    slug: 'andisheh-academic-center',
    name: 'Andisheh Academic Center',
    shortDescription: 'Konkur preparation, maths and physics',
    description:
      'Intensive Konkur preparation with weekly mock exams and personalised study plans for '
      + 'mathematics, physics and chemistry.',
    address: 'No. 210, Shariati St, Tehran',
    city: 'Tehran',
    province: 'Tehran',
    lat: 35.7420,
    lng: 51.4390,
    phone: '09122334455',
    categorySlugs: ['academic-tutoring', 'test-prep'],
    skills: ['konkur', 'mathematics', 'physics', 'chemistry'],
    amenities: ['library', 'study-hall', 'wifi'],
    verification: 'VERIFIED',
    published: true,
    freePreRegistration: false,
    commissionPercent: 10,
    targetRating: 4.3,
    reviewCount: 11,
  },
  {
    slug: 'honar-art-studio',
    name: 'Honar Art Studio',
    shortDescription: 'Painting, sketching and digital illustration',
    description:
      'A working studio offering classical painting technique and modern digital illustration, '
      + 'with a permanent gallery of student work.',
    address: 'No. 33, Karimkhan Blvd, Tehran',
    city: 'Tehran',
    province: 'Tehran',
    lat: 35.7135,
    lng: 51.4130,
    phone: '09188990011',
    categorySlugs: ['arts'],
    skills: ['painting', 'sketching', 'digital-art', 'photoshop'],
    amenities: ['studio-space', 'materials-included', 'gallery'],
    verification: 'VERIFIED',
    published: true,
    freePreRegistration: true,
    commissionPercent: 9,
    targetRating: 4.5,
    reviewCount: 6,
  },
  {
    slug: 'sadra-business-school',
    name: 'Sadra Business School',
    shortDescription: 'MBA-style short courses and accounting',
    description:
      'Practical management, accounting and digital marketing courses aimed at working '
      + 'professionals. Evening and weekend schedules.',
    address: 'No. 77, Mirdamad Blvd, Tehran',
    city: 'Tehran',
    province: 'Tehran',
    lat: 35.7605,
    lng: 51.4290,
    phone: '09126701234',
    categorySlugs: ['business'],
    skills: ['accounting', 'marketing', 'management', 'excel'],
    amenities: ['parking', 'wifi', 'conference-room'],
    verification: 'VERIFIED',
    published: true,
    freePreRegistration: true,
    commissionPercent: 15,
    targetRating: 4.1,
    reviewCount: 8,
  },
  {
    slug: 'alborz-sports-club',
    name: 'Alborz Sports Club',
    shortDescription: 'Swimming, martial arts and fitness',
    description:
      'Certified coaching for swimming, karate and general fitness, with separate schedules and '
      + 'facilities for all age groups.',
    address: 'No. 5, Niavaran St, Tehran',
    city: 'Tehran',
    province: 'Tehran',
    lat: 35.8130,
    lng: 51.4700,
    phone: '09122801122',
    categorySlugs: ['sports'],
    skills: ['swimming', 'karate', 'fitness', 'yoga'],
    amenities: ['pool', 'locker-rooms', 'parking', 'sauna'],
    verification: 'VERIFIED',
    published: true,
    freePreRegistration: true,
    commissionPercent: 10,
    targetRating: 4.4,
    reviewCount: 10,
  },
  {
    slug: 'goftegoo-language-house',
    name: 'Goftegoo Language House',
    shortDescription: 'German, French and Spanish',
    description:
      'European language courses following the CEFR framework, from A1 through C1, with official '
      + 'exam preparation for Goethe and DELF.',
    address: 'No. 19, Jordan St, Tehran',
    city: 'Tehran',
    province: 'Tehran',
    lat: 35.7680,
    lng: 51.4180,
    phone: '09188221133',
    categorySlugs: ['languages'],
    skills: ['german', 'french', 'spanish', 'goethe', 'delf'],
    amenities: ['wifi', 'library'],
    verification: 'PENDING',
    published: true,
    freePreRegistration: true,
    commissionPercent: 10,
    targetRating: 4.2,
    reviewCount: 5,
  },
  {
    slug: 'daneshvar-tutoring',
    name: 'Daneshvar Tutoring',
    shortDescription: 'Primary and secondary school support',
    description: 'After-school tutoring for grades 1 to 12, in small groups or one-to-one.',
    address: 'No. 91, Sattarkhan St, Tehran',
    city: 'Tehran',
    province: 'Tehran',
    lat: 35.7150,
    lng: 51.3390,
    phone: '09144556677',
    categorySlugs: ['academic-tutoring'],
    skills: ['mathematics', 'literature', 'english', 'science'],
    amenities: ['wifi', 'study-hall'],
    verification: 'PENDING',
    published: true,
    freePreRegistration: true,
    commissionPercent: 10,
    targetRating: 3.9,
    reviewCount: 4,
  },
  {
    slug: 'rayan-tech-academy',
    name: 'Rayan Tech Academy',
    shortDescription: 'Data science and cloud engineering',
    description: 'Advanced courses in data engineering, machine learning and cloud infrastructure.',
    address: 'No. 64, Saadat Abad, Tehran',
    city: 'Tehran',
    province: 'Tehran',
    lat: 35.7830,
    lng: 51.3720,
    phone: '09188445566',
    categorySlugs: ['programming'],
    skills: ['data-science', 'machine-learning', 'aws', 'docker', 'python'],
    amenities: ['wifi', 'lab', 'parking'],
    verification: 'UNVERIFIED',
    published: true,
    freePreRegistration: false,
    commissionPercent: 12,
    targetRating: 3.4,
    reviewCount: 3,
  },
  {
    slug: 'mehr-conservatory',
    name: 'Mehr Conservatory',
    shortDescription: 'Choir, guitar and music theory',
    description: 'Group music education with a focus on choir, guitar and formal music theory.',
    address: 'No. 12, Gisha Bridge, Tehran',
    city: 'Tehran',
    province: 'Tehran',
    lat: 35.7355,
    lng: 51.3690,
    phone: '09188337744',
    categorySlugs: ['music'],
    skills: ['guitar', 'choir', 'music-theory'],
    amenities: ['wifi', 'practice-rooms'],
    verification: 'UNVERIFIED',
    published: true,
    freePreRegistration: true,
    commissionPercent: 10,
    targetRating: 4.0,
    reviewCount: 4,
  },
  {
    slug: 'draft-institute-preview',
    name: 'Draft Institute (unpublished)',
    shortDescription: 'Not yet visible in public search',
    description:
      'Exists to prove that unpublished institutes never appear in discovery results.',
    address: 'No. 1, Test St, Tehran',
    city: 'Tehran',
    province: 'Tehran',
    lat: 35.7000,
    lng: 51.3500,
    phone: '09100000000',
    categorySlugs: ['languages'],
    skills: ['english'],
    amenities: [],
    verification: 'REJECTED',
    published: false,
    freePreRegistration: true,
    commissionPercent: 10,
    targetRating: 0,
    reviewCount: 0,
  },
];

export interface SeedCourse {
  instituteSlug: string;
  slug: string;
  title: string;
  description: string;
  type: 'ONLINE' | 'IN_PERSON' | 'HYBRID';
  level: 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED' | 'ALL_LEVELS';
  /** Rial. */
  price: number;
  discountPercent: number;
  durationHours: number;
  capacity: number;
  categorySlug: string;
  published: boolean;
  sessions: { dayOfWeek: number; startTime: string; endTime: string; room: string | null }[];
}

export const COURSES: SeedCourse[] = [
  {
    instituteSlug: 'pardis-language-academy',
    slug: 'ielts-intensive-band-7',
    title: 'IELTS Intensive — Band 7+',
    description: 'Twelve weeks of exam technique, mock tests and one-to-one speaking practice.',
    type: 'IN_PERSON',
    level: 'ADVANCED',
    price: 18_500_000,
    discountPercent: 15,
    durationHours: 72,
    capacity: 16,
    categorySlug: 'test-prep',
    published: true,
    sessions: [
      { dayOfWeek: 6, startTime: '17:30', endTime: '20:00', room: 'Room A' },
      { dayOfWeek: 1, startTime: '17:30', endTime: '20:00', room: 'Room A' },
    ],
  },
  {
    instituteSlug: 'pardis-language-academy',
    slug: 'general-english-b1',
    title: 'General English B1',
    description: 'Build confident everyday English across all four skills.',
    type: 'HYBRID',
    level: 'INTERMEDIATE',
    price: 9_800_000,
    discountPercent: 0,
    durationHours: 48,
    capacity: 20,
    categorySlug: 'languages',
    published: true,
    sessions: [{ dayOfWeek: 3, startTime: '18:00', endTime: '20:00', room: 'Room B' }],
  },
  {
    instituteSlug: 'pardis-language-academy',
    slug: 'business-english-online',
    title: 'Business English (Online)',
    description: 'Meetings, negotiation and professional writing, taught entirely online.',
    type: 'ONLINE',
    level: 'INTERMEDIATE',
    price: 7_500_000,
    discountPercent: 10,
    durationHours: 30,
    capacity: 30,
    categorySlug: 'languages',
    published: true,
    sessions: [{ dayOfWeek: 2, startTime: '19:00', endTime: '20:30', room: null }],
  },
  {
    instituteSlug: 'tehran-code-school',
    slug: 'fullstack-web-bootcamp',
    title: 'Full-Stack Web Bootcamp',
    description: 'React, Node.js and PostgreSQL, culminating in a deployed capstone project.',
    type: 'IN_PERSON',
    level: 'BEGINNER',
    price: 42_000_000,
    discountPercent: 20,
    durationHours: 240,
    capacity: 24,
    categorySlug: 'programming',
    published: true,
    sessions: [
      { dayOfWeek: 6, startTime: '09:00', endTime: '13:00', room: 'Lab 1' },
      { dayOfWeek: 2, startTime: '09:00', endTime: '13:00', room: 'Lab 1' },
      { dayOfWeek: 4, startTime: '09:00', endTime: '13:00', room: 'Lab 1' },
    ],
  },
  {
    instituteSlug: 'tehran-code-school',
    slug: 'flutter-mobile-development',
    title: 'Flutter Mobile Development',
    description: 'Ship a cross-platform app to both stores, from widgets to release builds.',
    type: 'ONLINE',
    level: 'INTERMEDIATE',
    price: 22_000_000,
    discountPercent: 0,
    durationHours: 90,
    capacity: 40,
    categorySlug: 'programming',
    published: true,
    sessions: [{ dayOfWeek: 0, startTime: '19:00', endTime: '21:30', room: null }],
  },
  {
    instituteSlug: 'tehran-code-school',
    slug: 'python-for-beginners',
    title: 'Python for Beginners',
    description: 'Programming fundamentals with Python, no prior experience needed.',
    type: 'HYBRID',
    level: 'BEGINNER',
    price: 12_000_000,
    discountPercent: 5,
    durationHours: 60,
    capacity: 28,
    categorySlug: 'programming',
    published: true,
    sessions: [{ dayOfWeek: 1, startTime: '18:30', endTime: '21:00', room: 'Lab 2' }],
  },
  {
    instituteSlug: 'nava-music-institute',
    slug: 'piano-foundations',
    title: 'Piano Foundations',
    description: 'One-to-one piano tuition covering technique, sight-reading and repertoire.',
    type: 'IN_PERSON',
    level: 'BEGINNER',
    price: 15_000_000,
    discountPercent: 0,
    durationHours: 40,
    capacity: 8,
    categorySlug: 'music',
    published: true,
    sessions: [{ dayOfWeek: 5, startTime: '16:00', endTime: '17:30', room: 'Studio 1' }],
  },
  {
    instituteSlug: 'nava-music-institute',
    slug: 'setar-traditional',
    title: 'Setar — Traditional Repertoire',
    description: 'Radif-based setar instruction from foundation through intermediate.',
    type: 'IN_PERSON',
    level: 'ALL_LEVELS',
    price: 13_500_000,
    discountPercent: 10,
    durationHours: 36,
    capacity: 10,
    categorySlug: 'music',
    published: true,
    sessions: [{ dayOfWeek: 0, startTime: '17:00', endTime: '18:30', room: 'Studio 2' }],
  },
  {
    instituteSlug: 'andisheh-academic-center',
    slug: 'konkur-mathematics',
    title: 'Konkur Mathematics — Full Course',
    description: 'Complete Konkur mathematics syllabus with weekly timed mock exams.',
    type: 'IN_PERSON',
    level: 'ADVANCED',
    price: 28_000_000,
    discountPercent: 0,
    durationHours: 160,
    capacity: 35,
    categorySlug: 'academic-tutoring',
    published: true,
    sessions: [
      { dayOfWeek: 5, startTime: '08:00', endTime: '12:00', room: 'Hall 1' },
      { dayOfWeek: 3, startTime: '16:00', endTime: '19:00', room: 'Hall 1' },
    ],
  },
  {
    instituteSlug: 'andisheh-academic-center',
    slug: 'physics-online-intensive',
    title: 'Physics Online Intensive',
    description: 'Live online physics problem-solving with recorded catch-up sessions.',
    type: 'ONLINE',
    level: 'ADVANCED',
    price: 16_000_000,
    discountPercent: 12,
    durationHours: 80,
    capacity: 60,
    categorySlug: 'academic-tutoring',
    published: true,
    sessions: [{ dayOfWeek: 4, startTime: '20:00', endTime: '22:00', room: null }],
  },
  {
    instituteSlug: 'honar-art-studio',
    slug: 'oil-painting-basics',
    title: 'Oil Painting Basics',
    description: 'Colour theory, composition and brushwork. All materials provided.',
    type: 'IN_PERSON',
    level: 'BEGINNER',
    price: 11_000_000,
    discountPercent: 0,
    durationHours: 32,
    capacity: 14,
    categorySlug: 'arts',
    published: true,
    sessions: [{ dayOfWeek: 1, startTime: '15:00', endTime: '18:00', room: 'Studio A' }],
  },
  {
    instituteSlug: 'honar-art-studio',
    slug: 'digital-illustration',
    title: 'Digital Illustration with Photoshop',
    description: 'From sketch to finished digital artwork, taught live online.',
    type: 'ONLINE',
    level: 'INTERMEDIATE',
    price: 9_000_000,
    discountPercent: 25,
    durationHours: 24,
    capacity: 25,
    categorySlug: 'arts',
    published: true,
    sessions: [{ dayOfWeek: 6, startTime: '10:00', endTime: '12:00', room: null }],
  },
  {
    instituteSlug: 'sadra-business-school',
    slug: 'digital-marketing-essentials',
    title: 'Digital Marketing Essentials',
    description: 'SEO, paid social and analytics for small businesses.',
    type: 'HYBRID',
    level: 'BEGINNER',
    price: 14_500_000,
    discountPercent: 10,
    durationHours: 45,
    capacity: 30,
    categorySlug: 'business',
    published: true,
    sessions: [{ dayOfWeek: 2, startTime: '18:00', endTime: '21:00', room: 'Room 1' }],
  },
  {
    instituteSlug: 'sadra-business-school',
    slug: 'financial-accounting',
    title: 'Financial Accounting',
    description: 'Bookkeeping through to financial statements, with Excel workshops.',
    type: 'IN_PERSON',
    level: 'INTERMEDIATE',
    price: 17_000_000,
    discountPercent: 0,
    durationHours: 55,
    capacity: 22,
    categorySlug: 'business',
    published: true,
    sessions: [{ dayOfWeek: 0, startTime: '17:00', endTime: '20:00', room: 'Room 2' }],
  },
  {
    instituteSlug: 'alborz-sports-club',
    slug: 'swimming-beginners',
    title: 'Swimming for Beginners',
    description: 'Water confidence and front crawl technique in a heated pool.',
    type: 'IN_PERSON',
    level: 'BEGINNER',
    price: 8_000_000,
    discountPercent: 0,
    durationHours: 20,
    capacity: 12,
    categorySlug: 'sports',
    published: true,
    sessions: [{ dayOfWeek: 6, startTime: '07:00', endTime: '08:00', room: 'Pool' }],
  },
  {
    instituteSlug: 'alborz-sports-club',
    slug: 'karate-youth',
    title: 'Karate — Youth Programme',
    description: 'Structured karate training for ages 8 to 16, working towards belt grading.',
    type: 'IN_PERSON',
    level: 'ALL_LEVELS',
    price: 6_500_000,
    discountPercent: 15,
    durationHours: 48,
    capacity: 20,
    categorySlug: 'sports',
    published: true,
    sessions: [{ dayOfWeek: 1, startTime: '16:00', endTime: '17:30', room: 'Dojo' }],
  },
  {
    instituteSlug: 'goftegoo-language-house',
    slug: 'german-a1',
    title: 'German A1',
    description: 'Absolute beginner German following the CEFR A1 syllabus.',
    type: 'IN_PERSON',
    level: 'BEGINNER',
    price: 10_500_000,
    discountPercent: 0,
    durationHours: 60,
    capacity: 18,
    categorySlug: 'languages',
    published: true,
    sessions: [{ dayOfWeek: 3, startTime: '17:00', endTime: '19:00', room: 'Room 1' }],
  },
  {
    instituteSlug: 'goftegoo-language-house',
    slug: 'french-conversation-online',
    title: 'French Conversation (Online)',
    description: 'Small-group spoken French with a native-speaker tutor.',
    type: 'ONLINE',
    level: 'INTERMEDIATE',
    price: 6_800_000,
    discountPercent: 5,
    durationHours: 24,
    capacity: 12,
    categorySlug: 'languages',
    published: true,
    sessions: [{ dayOfWeek: 4, startTime: '19:30', endTime: '21:00', room: null }],
  },
  {
    instituteSlug: 'daneshvar-tutoring',
    slug: 'grade-9-mathematics',
    title: 'Grade 9 Mathematics',
    description: 'Full-year support for the grade 9 mathematics curriculum.',
    type: 'IN_PERSON',
    level: 'ALL_LEVELS',
    price: 7_200_000,
    discountPercent: 0,
    durationHours: 64,
    capacity: 15,
    categorySlug: 'academic-tutoring',
    published: true,
    sessions: [{ dayOfWeek: 2, startTime: '16:00', endTime: '18:00', room: 'Class 1' }],
  },
  {
    instituteSlug: 'rayan-tech-academy',
    slug: 'machine-learning-foundations',
    title: 'Machine Learning Foundations',
    description: 'Supervised learning, model evaluation and deployment with scikit-learn.',
    type: 'ONLINE',
    level: 'ADVANCED',
    price: 32_000_000,
    discountPercent: 0,
    durationHours: 100,
    capacity: 35,
    categorySlug: 'programming',
    published: true,
    sessions: [{ dayOfWeek: 5, startTime: '14:00', endTime: '17:00', room: null }],
  },
  {
    instituteSlug: 'mehr-conservatory',
    slug: 'classical-guitar',
    title: 'Classical Guitar',
    description: 'Classical guitar technique and repertoire in small groups.',
    type: 'IN_PERSON',
    level: 'BEGINNER',
    price: 9_500_000,
    discountPercent: 0,
    durationHours: 30,
    capacity: 10,
    categorySlug: 'music',
    published: true,
    sessions: [{ dayOfWeek: 0, startTime: '18:00', endTime: '19:30', room: 'Room A' }],
  },
  {
    instituteSlug: 'tehran-code-school',
    slug: 'draft-devops-course',
    title: 'DevOps Fundamentals (draft)',
    description: 'Unpublished on purpose: proves drafts stay out of public listings.',
    type: 'ONLINE',
    level: 'INTERMEDIATE',
    price: 20_000_000,
    discountPercent: 0,
    durationHours: 50,
    capacity: 20,
    categorySlug: 'programming',
    published: false,
    sessions: [],
  },
];

export interface SeedInstructor {
  instituteSlug: string;
  fullName: string;
  headline: string;
  bio: string;
  yearsOfExperience: number;
  specialties: string[];
  rating: number;
  reviewCount: number;
}

export const INSTRUCTORS: SeedInstructor[] = [
  {
    instituteSlug: 'pardis-language-academy',
    fullName: 'Dr. Nima Rasouli',
    headline: 'Cambridge CELTA · 12 years teaching IELTS',
    bio: 'Former IELTS examiner who has guided more than 1,500 candidates to band 7 and above.',
    yearsOfExperience: 12,
    specialties: ['ielts', 'academic-writing'],
    rating: 4.8,
    reviewCount: 64,
  },
  {
    instituteSlug: 'pardis-language-academy',
    fullName: 'Sara Kamali',
    headline: 'Business English specialist',
    bio: 'Designs in-company English programmes for engineering and finance teams.',
    yearsOfExperience: 8,
    specialties: ['business-english', 'presentation-skills'],
    rating: 4.6,
    reviewCount: 41,
  },
  {
    instituteSlug: 'tehran-code-school',
    fullName: 'Reza Mohammadi',
    headline: 'Senior full-stack engineer',
    bio: 'Ten years building production React and Node systems; leads the capstone reviews.',
    yearsOfExperience: 10,
    specialties: ['react', 'nodejs', 'postgresql'],
    rating: 4.9,
    reviewCount: 88,
  },
  {
    instituteSlug: 'tehran-code-school',
    fullName: 'Mina Tabatabaei',
    headline: 'Mobile lead · Flutter GDE',
    bio: 'Has shipped a dozen Flutter apps and mentors the mobile track end to end.',
    yearsOfExperience: 7,
    specialties: ['flutter', 'dart', 'mobile-architecture'],
    rating: 4.8,
    reviewCount: 52,
  },
  {
    instituteSlug: 'nava-music-institute',
    fullName: 'Ostad Bahram Ghaderi',
    headline: 'Setar master · Tehran Conservatory',
    bio: 'Thirty years performing and teaching the traditional Persian radif.',
    yearsOfExperience: 30,
    specialties: ['setar', 'tar', 'radif'],
    rating: 4.9,
    reviewCount: 37,
  },
  {
    instituteSlug: 'andisheh-academic-center',
    fullName: 'Dr. Hossein Ahmadi',
    headline: 'Konkur mathematics · 15 years',
    bio: 'Author of two Konkur preparation workbooks used across the country.',
    yearsOfExperience: 15,
    specialties: ['mathematics', 'konkur'],
    rating: 4.5,
    reviewCount: 73,
  },
  {
    instituteSlug: 'honar-art-studio',
    fullName: 'Leila Farahani',
    headline: 'Painter · exhibited nationally',
    bio: 'Works in oil and mixed media; teaches classical technique with a contemporary eye.',
    yearsOfExperience: 14,
    specialties: ['oil-painting', 'composition'],
    rating: 4.7,
    reviewCount: 29,
  },
  {
    instituteSlug: 'sadra-business-school',
    fullName: 'Amir Hosseini',
    headline: 'CFO turned lecturer',
    bio: 'Twenty years in corporate finance, now teaching accounting to founders.',
    yearsOfExperience: 20,
    specialties: ['accounting', 'financial-analysis'],
    rating: 4.2,
    reviewCount: 33,
  },
  {
    instituteSlug: 'alborz-sports-club',
    fullName: 'Coach Yaser Norouzi',
    headline: 'National swimming coach',
    bio: 'Coaches beginners through to competitive squad swimmers.',
    yearsOfExperience: 11,
    specialties: ['swimming', 'water-safety'],
    rating: 4.6,
    reviewCount: 45,
  },
  {
    instituteSlug: 'goftegoo-language-house',
    fullName: 'Elham Mousavi',
    headline: 'Goethe-certified German instructor',
    bio: 'Prepares candidates for Goethe A1 to B2 examinations.',
    yearsOfExperience: 9,
    specialties: ['german', 'goethe'],
    rating: 4.4,
    reviewCount: 26,
  },
  {
    instituteSlug: 'rayan-tech-academy',
    fullName: 'Dr. Kaveh Sadeghi',
    headline: 'Data scientist · PhD',
    bio: 'Applies machine learning in industry and teaches the ML foundations track.',
    yearsOfExperience: 9,
    specialties: ['machine-learning', 'python'],
    rating: 4.3,
    reviewCount: 18,
  },
  {
    instituteSlug: 'mehr-conservatory',
    fullName: 'Peyman Arefi',
    headline: 'Classical guitarist',
    bio: 'Conservatory-trained guitarist teaching technique and ensemble playing.',
    yearsOfExperience: 13,
    specialties: ['guitar', 'music-theory'],
    rating: 4.5,
    reviewCount: 21,
  },
  {
    instituteSlug: 'daneshvar-tutoring',
    fullName: 'Fatemeh Karimi',
    headline: 'Secondary mathematics teacher',
    bio: 'Fifteen years in secondary education, specialising in exam confidence.',
    yearsOfExperience: 15,
    specialties: ['mathematics', 'study-skills'],
    rating: 4.1,
    reviewCount: 19,
  },
];

/** Review sentences, cycled deterministically to keep the seed reproducible. */
export const REVIEW_TEXTS: { title: string; body: string }[] = [
  { title: 'Genuinely excellent', body: 'The teaching was structured and the feedback was specific. I improved much faster than I expected.' },
  { title: 'Great instructors', body: 'Instructors clearly know the material and care whether you understand it. Classrooms are comfortable.' },
  { title: 'Worth the money', body: 'Not the cheapest option, but the small class sizes make a real difference to how much you speak.' },
  { title: 'Well organised', body: 'Everything ran on time, materials were shared in advance and admin were easy to reach.' },
  { title: 'Helped me reach my goal', body: 'I got the score I needed on the first attempt. The mock exams were the most useful part.' },
  { title: 'Good, with caveats', body: 'Teaching is strong, though the building can be noisy in the evenings. Still recommend it.' },
  { title: 'Friendly atmosphere', body: 'Welcoming from the first session, which mattered a lot as a nervous beginner.' },
  { title: 'Practical and hands-on', body: 'Far more project work than theory, which is exactly what I was looking for.' },
  { title: 'Solid teaching', body: 'Clear explanations and patient with questions. Would take another course here.' },
  { title: 'Room for improvement', body: 'The content is good but the schedule changed twice, which was inconvenient.' },
  { title: 'Highly recommended', body: 'I have taken courses at three institutes and this was by far the most professional.' },
  { title: 'Very supportive', body: 'They followed up after every assessment with concrete things to work on.' },
  { title: 'Good value', body: 'Reasonable price for the number of contact hours, and the materials are included.' },
  { title: 'Knowledgeable staff', body: 'Questions never went unanswered, even outside class time.' },
];
